export const MARK_AS_READ_PATIENT_MESSAGES         = 'App/MARK_AS_READ_PATIENT_MESSAGES';

export const DELETE_MESSAGES_COUNT_STAT            = 'App/DELETE_MESSAGES_COUNT_STAT';

export const SUBTRACT_STUDY_UNREAD_MESSAGES             = 'HomePage/Viewport/SUBTRACT_STUDY_UNREAD_MESSAGES';

export const INCREMENT_STUDY_UNREAD_MESSAGES             = 'HomePage/Viewport/INCREMENT_STUDY_UNREAD_MESSAGES';

