/*
 *
 * ListNewStudyPage constants
 *
 */

export const SHOW_ADD_SITE_LOCATION_MODAL = 'ListNewStudyPage/SHOW_ADD_SITE_LOCATION_MODAL';
export const HIDE_ADD_SITE_LOCATION_MODAL = 'ListNewStudyPage/HIDE_ADD_SITE_LOCATION_MODAL';

export const SHOW_ADD_EMAIL_MODAL = 'ListNewStudyPage/SHOW_ADD_EMAIL_MODAL';
export const HIDE_ADD_EMAIL_MODAL = 'ListNewStudyPage/HIDE_ADD_EMAIL_MODAL';

export const SUBMIT_FORM = 'ListNewStudyPage/SUBMIT_FORM';
export const SUBMIT_FORM_SUCCESS = 'ListNewStudyPage/SUBMIT_FORM_SUCCESS';
export const SUBMIT_FORM_ERROR = 'ListNewStudyPage/SUBMIT_FORM_ERROR';

export const GET_AVAIL_PHONE_NUMBERS = 'ListNewStudyPage/GET_AVAIL_PHONE_NUMBERS';
export const GET_AVAIL_PHONE_NUMBERS_SUCCESS = 'ListNewStudyPage/GET_AVAIL_PHONE_NUMBERS_SUCCESS';
export const GET_AVAIL_PHONE_NUMBERS_ERROR = 'ListNewStudyPage/GET_AVAIL_PHONE_NUMBERS_ERROR';

export const HIDE_SUBMIT_FORM_MODAL = 'ListNewStudyPage/HIDE_SUBMIT_FORM_MODAL';

