/*
 *
 * StudyPage constants
 *
 */

/* eslint-disable no-multi-spaces */

export const FETCH_CAMPAIGNS_SUCCESS  = 'StudyPage/FETCH_CAMPAIGNS_SUCCESS';
export const FETCH_PATIENTS = 'StudyPage/FETCH_PATIENTS';
export const FETCH_PATIENTS_SUCCESS  = 'StudyPage/FETCH_PATIENTS_SUCCESS';
export const FETCH_PATIENT_DETAILS = 'StudyPage/FETCH_PATIENT_DETAILS';
export const FETCH_PATIENT_DETAILS_SUCCESS  = 'StudyPage/FETCH_PATIENT_DETAILS_SUCCESS';
export const FETCH_PATIENT_CATEGORIES  = 'StudyPage/FETCH_PATIENT_CATEGORIES';
export const FETCH_PATIENT_CATEGORIES_SUCCESS  = 'StudyPage/FETCH_PATIENT_CATEGORIES_SUCCESS';
export const FETCH_STUDY  = 'StudyPage/FETCH_STUDY';
export const FETCH_SITE_SUCCESS  = 'StudyPage/FETCH_SITE_SUCCESS';
export const FETCH_SOURCES_SUCCESS  = 'StudyPage/FETCH_SOURCES_SUCCESS';
export const FETCH_STUDY_SUCCESS  = 'StudyPage/FETCH_STUDY_SUCCESS';
export const SET_CURRENT_PATIENT_ID    = 'StudyPage/SET_CURRENT_PATIENT_ID';
export const SET_CURRENT_PATIENT_CATEGORY_ID    = 'StudyPage/SET_CURRENT_PATIENT_CATEGORY_ID';
export const SUBMIT_PATIENT_UPDATE    = 'StudyPage/SUBMIT_PATIENT_UPDATE';
export const UPDATE_PATIENT_SUCCESS    = 'StudyPage/UPDATE_PATIENT_SUCCESS';
export const SUBMIT_TEXT_BLAST    = 'StudyPage/SUBMIT_TEXT_BLAST';
export const SUBMIT_PATIENT_IMPORT    = 'StudyPage/SUBMIT_PATIENT_IMPORT';
export const SUBMIT_ADD_PATIENT    = 'StudyPage/SUBMIT_ADD_PATIENT';
