/*
 *
 * StudyPage constants
 *
 */

/* eslint-disable no-multi-spaces */

export const FIND_PATIENTS_TEXT_BLAST = 'StudyPage/FIND_PATIENTS_TEXT_BLAST';
export const FIND_PATIENTS_TEXT_BLAST_SUCCESS = 'StudyPage/FIND_PATIENTS_TEXT_BLAST_SUCCESS';
export const FILTER_PATIENTS_TEXT_BLAST = 'StudyPage/FILTER_PATIENTS_TEXT_BLAST';
export const ADD_PATIENT_TO_TEXT_BLAST = 'StudyPage/ADD_PATIENT_TO_TEXT_BLAST';
export const REMOVE_PATIENT_FROM_TEXT_BLAST = 'StudyPage/REMOVE_PATIENT_FROM_TEXT_BLAST';
export const FETCH_CAMPAIGNS_SUCCESS  = 'StudyPage/FETCH_CAMPAIGNS_SUCCESS';
export const FETCH_PATIENTS = 'StudyPage/FETCH_PATIENTS';
export const FETCH_PATIENTS_SUCCESS  = 'StudyPage/FETCH_PATIENTS_SUCCESS';
export const FETCH_PATIENT_DETAILS = 'StudyPage/FETCH_PATIENT_DETAILS';
export const FETCH_PATIENT_DETAILS_SUCCESS  = 'StudyPage/FETCH_PATIENT_DETAILS_SUCCESS';
export const FETCH_PATIENT_CATEGORIES  = 'StudyPage/FETCH_PATIENT_CATEGORIES';
export const FETCH_PATIENT_CATEGORIES_SUCCESS  = 'StudyPage/FETCH_PATIENT_CATEGORIES_SUCCESS';
export const FETCH_STUDY  = 'StudyPage/FETCH_STUDY';
export const FETCH_SITE_SUCCESS  = 'StudyPage/FETCH_SITE_SUCCESS';
export const FETCH_SOURCES_SUCCESS  = 'StudyPage/FETCH_SOURCES_SUCCESS';
export const FETCH_STUDY_SUCCESS  = 'StudyPage/FETCH_STUDY_SUCCESS';
export const FETCH_STUDY_VIEWS_SUCCESS  = 'StudyPage/FETCH_STUDY_VIEWS_SUCCESS';
export const FETCH_STUDY_PATIENT_REFERRALS_SUCCESS  = 'StudyPage/FETCH_STUDY_PATIENT_REFERRALS_SUCCESS';
export const FETCH_STUDY_CALLS_SUCCESS  = 'StudyPage/FETCH_STUDY_CALLS_SUCCESS';
export const FETCH_STUDY_TEXTS_SUCCESS  = 'StudyPage/FETCH_STUDY_TEXTS_SUCCESS';
export const SET_STUDY_ID    = 'StudyPage/SET_STUDY_ID';
export const SET_SITE_ID    = 'StudyPage/SET_SITE_ID';
export const SET_CURRENT_PATIENT_ID    = 'StudyPage/SET_CURRENT_PATIENT_ID';
export const SET_CURRENT_PATIENT_CATEGORY_ID    = 'StudyPage/SET_CURRENT_PATIENT_CATEGORY_ID';
export const SUBMIT_MOVE_PATIENT_BETWEEN_CATEGORIES    = 'StudyPage/SUBMIT_MOVE_PATIENT_BETWEEN_CATEGORIES';
export const MOVE_PATIENT_BETWEEN_CATEGORIES_LOADING    = 'StudyPage/MOVE_PATIENT_BETWEEN_CATEGORIES_LOADING';
export const MOVE_PATIENT_BETWEEN_CATEGORIES_SUCCESS    = 'StudyPage/MOVE_PATIENT_BETWEEN_CATEGORIES_SUCCESS';
export const MOVE_PATIENT_BETWEEN_CATEGORIES_FAILED    = 'StudyPage/MOVE_PATIENT_BETWEEN_CATEGORIES_FAILED';
export const SUBMIT_TEXT_BLAST    = 'StudyPage/SUBMIT_TEXT_BLAST';
export const SUBMIT_PATIENT_IMPORT    = 'StudyPage/SUBMIT_PATIENT_IMPORT';
export const SUBMIT_ADD_PATIENT_INDICATION    = 'StudyPage/SUBMIT_ADD_PATIENT_INDICATION';
export const SUBMIT_REMOVE_PATIENT_INDICATION    = 'StudyPage/SUBMIT_REMOVE_PATIENT_INDICATION';
export const SUBMIT_PATIENT_UPDATE    = 'StudyPage/SUBMIT_PATIENT_UPDATE';
export const SUBMIT_PATIENT_NOTE    = 'StudyPage/SUBMIT_PATIENT_NOTE';
export const SUBMIT_DELETE_NOTE    = 'StudyPage/SUBMIT_DELETE_NOTE';
export const SUBMIT_DELETE_NOTE_SUCCESS    = 'StudyPage/SUBMIT_DELETE_NOTE_SUCCESS';
export const SUBMIT_PATIENT_TEXT    = 'StudyPage/SUBMIT_PATIENT_TEXT';
export const ADD_PATIENT_INDICATION_SUCCESS    = 'StudyPage/ADD_PATIENT_INDICATION_SUCCESS';
export const REMOVE_PATIENT_INDICATION_SUCCESS    = 'StudyPage/REMOVE_PATIENT_INDICATION_SUCCESS';
export const UPDATE_PATIENT_SUCCESS    = 'StudyPage/UPDATE_PATIENT_SUCCESS';
export const ADD_PATIENT_NOTE_SUCCESS    = 'StudyPage/ADD_PATIENT_NOTE_SUCCESS';
export const ADD_PATIENT_TEXT_SUCCESS    = 'StudyPage/UPDATE_PATIENT_SUCCESS';
export const SUBMIT_ADD_PATIENT    = 'StudyPage/SUBMIT_ADD_PATIENT';
