import React from 'react';
import BackToTopButton from '../../components/BackTopButton';

export default class TermsAndConditionsPage extends React.Component { // eslint-disable-line react/prefer-stateless-function

  static propTypes = {};

  render() {
    return (
      <div id="main">
        <div className="container">
          <section className="privacy-policy">
            <header className="text-center">
              <h2 className="main-heading">TERMS &amp; CONDITIONS</h2>
              <p>PLEASE READ THE FOLLOWING TERMS &amp; CONDITIONS CAREFULLY</p>
            </header>
            <hr className="divider" />
            <h3>DELIVERY METHODS AND TIMINGS</h3>
            <p>
              Each study listed on StudyKIK is up and running within 24 hours of payment (Monday through Friday).
              Each study runs for 30 days unless otherwise specified. Links to your study listing(s) will be emailed
              to you by a Project Manager within 24 hours of payment (Monday through Friday).
            </p>
            <p>
              By purchasing any products/services on this site, you agree to this disclaimer. If you do not agree,
              you should not use this site. Users under age 13 are prohibited.
            </p>
            <hr className="divider" />
            <h3>DISCLAIMER</h3>
            <p>
              The material in this site could include technical inaccuracies or typographical errors. StudyKIK
              may make changes or improvements at any time. THE MATERIALS IN THIS SITE ARE PROVIDED “AS
              IS” AND WITHOUT WARRANTIES OF ANY KIND EITHER EXPRESSED OR IMPLIED, TO THE FULLEST EXTENT PERMISSIBLE
              PURSUANT TO APPLICABLE LAW. STUDYKIK DOES NOT WARRANT THAT THE FUNCTIONS CONTAINED IN
              THE MATERIAL WILL BE UNINTERRUPTED OR ERROR-FREE, THAT DEFECTS WILL BE CORRECTED, OR THAT THIS SITE OR
              THE SERVER THAT MAKES IT AVAILABLE ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. STUDYKIK
              DOES NOT WARRANT OR MAKE ANY REPRESENTATIONS REGARDING THE USE OF OR THE RESULT OF THE USE OF
              THE MATERIAL IN THIS SITE IN TERMS OF THEIR CORRECTNESS, ACCURACY, RELIABILITY, OR OTHERWISE. YOU (AND
              NOT STUDUKIK) ASSUME THE ENTIRE COST OF ALL NECESSARY SERVICING, REPAIR OR CORRECTION.
              THE ABOVE EXCLUSION MAY NOT APPLY TO YOU, TO THE EXTENT THAT APPLICABLE LAW MAY NOT ALLOW THE
              EXCLUSION OF IMPLIED WARRANTIES.
            </p>
            <p>
              This website contains downloadable materials as well as links to external sites. StudyKIK is
              not responsible for, and has no control over, the content of such downloadable materials or external
              sites. You understand that StudyKIK cannot and does not guarantee or warrant that files or
              software of any kind, or from any source, available for downloading through this website, will be free
              of infection or viruses, worms, Trojan Horses or other code or defects that manifest contaminating or
              destructive properties.
            </p>
            <hr className="divider" />
            <h3>RESTRICTIONS ON USE</h3>
            <p>
              Material from StudyKIK or any of its sites may not be copied or distributed, or
              republished, uploaded, posted, or transmitted in any way, without the prior written consent of
              StudyKIK EXCEPT: you may download one copy of the material on one computer for your
              personal, non-commercial home use only, provided you do not delete or change any copyright,
              trademark, or other proprietary notices. Modification or use of the materials for any other purpose
              violates StudyKIK intellectual property rights. The material in this site is provided for
              lawful purposes only. If you download software from our site, the software, including all files,
              images, contained in or generated by the software, and accompanying data (together, the “Software”)
              are deemed to be licensed to you by StudyKIK. Neither title nor intellectual property rights
              are transferred to you, but remain with StudyKIK, who owns full and complete title. You may
              not resell, decompile, reverse engineer, disassemble, or otherwise convert the Software to a human
              perceivable form.
            </p>
            <hr className="divider" />
            <h3>RESTRICTION OF LIABILITY</h3>
            <p>
              StudyKIK will not be liable for any damages or injury caused by, including but not
              limited to, any failure of performance, error, omission, interruption, defect, delay in operation
              of transmission, computer virus, or line failure. StudyKIK will not be liable for any
              damages or injury, including but not limited to, special or consequential damages that result from
              the use of, or the inability to use, the materials in this site, even if there is negligence or
              StudyKIK or an authorized representative has been advised of the possibility of such
              damages, or both. The above limitation or exclusion may not apply to you to the extent that
              applicable law may not allow the limitation or exclusion of liability for incidental or
              consequential damages. StudyKIK total liability to you for all losses, damages, and causes
              of action (in contract, tort (including without limitation, negligence, or otherwise) will not be
              greater than the amount you paid to access this site.
            </p>
            <hr className="divider" />
            <h3>STUDY INFORMATION LISTED ON StudyKIK</h3>
            <p>
              All ads that are placed on the StudyKIK must be approved by an IRB. The research site takes
              responsibility of all advertisements placed. StudyKIK does ad disclaimer language under approved
              study language notifying those that enter information they will receive about the study location
              and details. Although most IRBs do not require this text to be approved, research sites must
              consult with IRB to make sure approval is not needed.
            </p>
            <hr className="divider" />
            <h3>SUBMISSIONS</h3>
            <p>
              All remarks, suggestions, ideas, graphics, or other information communicated to StudyKIK
              through this site (together, the “Submission”) will forever be the property of
              StudyKIK. StudyKIK will not be required to treat any Submission as
              confidential, and will not be liable for any ideas for its business (including without
              limitation, product, or advertising ideas) and will not incur any liability as a result of any
              similarities that may appear in future StudyKIK operations. Without limitation, StudyKIK
              will have exclusive ownership of all present and future existing rights to the
              Submission of every kind and nature everywhere. Except as noted below in this paragraph,
              StudyKIK will be entitled to use the Submission for any commercial or other purpose
              whatsoever without compensation to you or any other person sending the Submission. Personally
              identifiable information that may be received at this site is provided voluntarily by a
              visitor to this site. This information is for internal purposes only and is not sold or
              otherwise transferred to third parties of StudyKIK or to other entities who are not
              involved in the operation of this site. Information submitted via a number of areas in this
              site, for instance, Write to Ronald, is not retained. Therefore, the above right to use
              Submissions is subject to this limited use of this information and excludes non-retained
              information. You acknowledge that you are responsible for whatever material you submit, and
              you, not StudyKIK have full responsibility for the message, including its legality,
              reliability, appropriateness, originality, and copyright.
            </p>
            <hr className="divider" />
            <h3>REFUND POLICY</h3>
            <p>
              Once the cost of services is received by StudyKIK and services are rendered, no funds will
              be returned, reimbursed or credited in any circumstance, including where services are
              terminated by the contracting party prior to completion of services or in the event a
              campaign should close prior to completion of services. StudyKIK retains the right to
              revise this policy at any time.
            </p>
            <hr className="divider" />
            <h3>TERMINATION</h3>
            <p>
              StudyKIK or you may terminate this agreement at any time. You may terminate this
              agreement by destroying: (a) all materials obtained from all StudyKIK sites, and
              (b) all related documentation and all copies and installations(together, the “Materials”).
              StudyKIK may terminate this agreement immediately without notice if, in its sole
              judgment, you breach any term or condition of this agreement. Upon termination, you must
              destroy all materials.
            </p>
            <hr className="divider" />
            <h3>MISCELLANEOUS</h3>
            <p>
              These Terms and Conditions will be governed and be interpreted pursuant to the laws of
              the State of California, United States of America, notwithstanding any principles of
              conflicts of law. If any part of these Terms and Conditions is unlawful, void, or
              unenforceable, that part will be deemed severable and will not affect the validity and
              enforceability of any remaining provisions. Possible evidence of use of this site for
              illegal purposes will be provided to law enforcement authorities. This is the entire
              agreement between the parties relating to the use of this site. StudyKIK can
              revise these Terms and Conditions at any time by updating this posting. StudyKIK
              products and services are available in many parts of the world. However, the StudyKIK
              site may describe products and services that are not available worldwide. This
              site may be linked to other sites which are not maintained by StudyKIK. StudyKIK
              is not responsible for the content of those sites. The inclusion of any link
              to such sites does not imply endorsement by StudyKIK of the sites.
            </p>
          </section>
        </div>
        <BackToTopButton />
      </div>
    );
  }
}
