export default {
  client: [
    '/app/list-new-study',
    '/app/order-irb-ad-creation',
    '/app/request-proposal',
    '/app/refer',
    '/app/calendar',
    '/app/sites-users',
    '/app/patient-database',
    '/app/rewards',
    '/app/badges',
    '/app/me/profile',
    '/app/payment-information',
    '/app/receipts',
    '/app/proposals',
    '/confirm-password-change',
  ],
  sponsor: [
    '/app/calendar',
    '/app/manage-users',
    '/app/receipts-project-agreements',
    '/app/report',
    '/confirm-password-change',
  ],
  dashboard: [
    '/app/me/profile',
    '/app/dashboard-exposure-level',
    '/app/coupon',
    '/app/dashboard-indication',
    '/app/dashboard-protocol',
    '/app/dashboard-cro',
    '/app/dashboard-sponsor',
    '/app/dashboard-sponsor-admins',
    '/app/dashboard-client-admins',
    '/app/dashboard-manage-users',
    '/app/dashboard-reset-password',
    '/app/dashboard-locked-users',
    '/app/dashboard-portals',
    '/app/dashboard-messaging-numbers',
    '/app/dashboard-messaging-numbers/add',
    '/confirm-password-change',
  ],
};
