/* eslint-disable no-multi-spaces */

export const FETCH_PATIENTS_BY_STUDY          = 'CalendarPage/FETCH_PATIENTS_BY_STUDY';
export const FETCH_PATIENTS_BY_STUDY_SUCCESS  = 'CalendarPage/FETCH_PATIENTS_BY_STUDY_SUCCESS';
export const FETCH_PATIENTS_BY_STUDY_ERROR    = 'CalendarPage/FETCH_PATIENTS_BY_STUDY_ERROR';

export const FETCH_SCHEDULES          = 'CalendarPage/FETCH_SCHEDULES';
export const FETCH_SCHEDULES_SUCCESS  = 'CalendarPage/FETCH_SCHEDULES_SUCCESS';
export const FETCH_SCHEDULES_ERROR    = 'CalendarPage/FETCH_SCHEDULES_ERROR';

export const FETCH_SPONSOR_SCHEDULES          = 'CalendarPage/FETCH_SPONSOR_SCHEDULES';
export const FETCH_SPONSOR_SCHEDULES_SUCCESS  = 'CalendarPage/FETCH_SPONSOR_SCHEDULES_SUCCESS';
export const FETCH_SPONSOR_SCHEDULES_ERROR    = 'CalendarPage/FETCH_SPONSOR_SCHEDULES_ERROR';

export const FETCH_SPONSOR_PROTOCOLS          = 'CalendarPage/FETCH_SPONSOR_PROTOCOLS';
export const FETCH_SPONSOR_PROTOCOLS_SUCCESS  = 'CalendarPage/FETCH_SPONSOR_PROTOCOLS_SUCCESS';
export const FETCH_SPONSOR_PROTOCOLS_ERROR    = 'CalendarPage/FETCH_SPONSOR_PROTOCOLS_ERROR';

export const FETCH_SPONSOR_SITES          = 'CalendarPage/FETCH_SPONSOR_SITES';
export const FETCH_SPONSOR_SITES_SUCCESS  = 'CalendarPage/FETCH_SPONSOR_SITES_SUCCESS';
export const FETCH_SPONSOR_SITES_ERROR    = 'CalendarPage/FETCH_SPONSOR_SITES_ERROR';

export const SUBMIT_SCHEDULE         = 'CalendarPage/SUBMIT_SCHEDULE';
export const SUBMIT_SCHEDULE_SUCCESS = 'CalendarPage/SUBMIT_SCHEDULE_SUCCESS';
export const SUBMIT_SCHEDULE_ERROR   = 'CalendarPage/SUBMIT_SCHEDULE_ERROR';

export const DELETE_SCHEDULE         = 'CalendarPage/DELETE_SCHEDULE';
export const DELETE_SCHEDULE_SUCCESS = 'CalendarPage/DELETE_SCHEDULE_SUCCESS';
export const DELETE_SCHEDULE_ERROR   = 'CalendarPage/DELETE_SCHEDULE_ERROR';

export const SET_ACTIVE_SORT   = 'CalendarPage/SET_ACTIVE_SORT';
